name: GetSubInfo

on:
  push:
    branches: ["main"]
    paths:
      - '**.go'    
  pull_request:
    branches: ["main"]
    paths:
      - '**.go'

jobs:
  linux_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cross Compile
        run: GOOS=linux GOARCH=amd64 go build -o getsubinfo_linux_amd64
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: getsubinfo_linux_amd64
          path: getsubinfo_linux_amd64

  linux_arm64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cross Compile
        run: GOOS=linux GOARCH=arm64 go build -o getsubinfo_linux_arm64
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: getsubinfo_linux_arm64
          path: getsubinfo_linux_arm64

  darwin_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cross Compile
        run: GOOS=darwin GOARCH=amd64 go build -o getsubinfo_darwin_amd64
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: getsubinfo_darwin_amd64
          path: getsubinfo_darwin_amd64

  darwin_arm64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cross Compile
        run: GOOS=darwin GOARCH=arm64 go build -o getsubinfo_darwin_arm64
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: getsubinfo_darwin_arm64
          path: getsubinfo_darwin_arm64
  
  windows_amd64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cross Compile
        run: GOOS=windows GOARCH=amd64 go build -o getsubinfo_windows_amd64.exe
      - name: Upload Cross Compile Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: getsubinfo_windows_amd64
          path: getsubinfo_windows_amd64.exe
